### ISSUE TITLE
Weird behavior with custom extenders

### ISSUE THREAD

**Issue by larivierec** [Mottie/Keyboard#335]
Hello,

I have been using this keyboard for the past month and i've been having trouble understanding why the same code works in Debug and in normal "Release" mode it doesnt work.

Here is the snippet: 

```js
$.extend($.keyboard.keyaction, {
					
	enter: function(base,e){
		if (base.el.tagName === "INPUT") {
			if(base.el.id == "txtBoxAdminPass")
			{
				//$('#passbtn_click').click();
				base.accept();
				
				if (adminCheckPassword($('#txtBoxAdminPass').val()))
				{
					setAdminMode(true);
					$('#dialogPassword').dialog( "close" );
				}
				else
				{
					alert("Invalid Password");
				}
				txtBoxAdminPass.value = "";
			}
		}
	}
```

what happens is that if I use this exact code to check the password without a break point it goes right through it. If I add a breakpoint to this exact code, anywhere, it works... i'm not quite sure why.

Any guidance would be accepted... Also take note that they're no overwriting of the enter other than this location. 

This is contained in a dialog with options as follows:

```js
$( "#dialogPassword" ).dialog({
	autoOpen: false,
	modal: true,
	width: 450,
	height:200,
	enterNavigation:false,
	buttons: [
	{

		text: translate("ok_trans"),
		click: function() {
			var txtBoxAdminPass = document.getElementById("txtBoxAdminPass");
			if (adminCheckPassword(txtBoxAdminPass.value))
			{
				setAdminMode(true);
				$(this).dialog( "close" );
			}
			else
			{
				alert("Invalid Password");
			}
			txtBoxAdminPass.value = "";
		},
		id:'passbtn_click'
	},
	{
		text: translate("cancel_trans"),
		click: function() { $(this).dialog('close'); txtBoxAdminPass.value = "";}
	}]
});
```

and a text field with options: 

```js
$('#txtBoxAdminPass').keyboard({
	openOn: null,
	usePreview : false,
	maxLength : 12,
	autoAccept: true,
	enterNavigation:true
});
```

**Comment by Mottie** [comment]
Hi @larivierec!

If you look at the `accept` keyaction function, you'll see that it has a `return false` at the end. When a keyaction doesn't return false, the event continues to be processed... positioning the caret, checking for combination keys, and triggering a change event/callback. Essentially it acts as if the keyboard is to remain open.

So, after you call a `base.accept();`, add a `return false` immediately after it.

I'm not quite sure why the dialog initialization code has a `enterNavigation` option set to `false` in there, but it shouldn't be required. The keyboard plugin does have that option, but set to `true`. It won't work because of the change to the `enter` keyaction code. The default code includes a check for the `enterNavigation` option and calls the `base.switchInput` function, so you can copy that block over to the updated enter keyaction if you so desire.

Hopefully that will get things working as expected. If not, you can modify this demo I put together to show the issue that is occurring: http://jsfiddle.net/Mottie/egb3a1sk/133/

**Comment by larivierec** [comment]
Hello again, yes you are right concerning the enternavigation... ill take those off in the morning however, the base.accept() part is still weird. This function already has a return false; why would I have to add another one if it's already contained in it's function... secondly, i stated that this code that i had posted works with a Breakpoint and doesn't work without one.

**Comment by Mottie** [comment]
If you look at [line 663](https://github.com/Mottie/Keyboard/blob/master/js/jquery.keyboard.js#L663) you'll see that a `false` needs to be returned from within the keyaction function to stop further processing.

I can't tell exactly what is happening just from looking at the code... is the dialog ok button being used to validate the input, or the keyaction code for enter supposed to do that? 

Have you looked into using the [validate callback function](https://github.com/Mottie/Keyboard/wiki/Methods#validate)? Here is an [updated version](http://jsfiddle.net/Mottie/egb3a1sk/135/) of the demo I shared above with a validate function - it prevents the user from clicking accept when the password is invalid. I don't see why the dialog would need any buttons... 

If that isn't the way you want to use the keyboard, then please modify the demo so I can better understand your goal.

**Comment by larivierec** [comment]
Right, alright so the problem now is that if you are using a regular keyboard and I push the enter button it doesn't work. I modified the code a bit having tried the version with the accepted callback... 

When I use the actual keyboard it does not enter the accepted callback function specified is this because it is not being shown at the time of pushing enter?

Thanks again for your feedback,

**Comment by Mottie** [comment]
I added this to an [updated demo](http://jsfiddle.net/Mottie/egb3a1sk/139/) and it appears to work for me:

```js
$.keyboard.keyaction.enter = function(base, el){
    if (base.el.id == "txtBoxAdminPass") {
        base.accept();
        return false;
    }
};
```

**Comment by larivierec** [comment]
Right... I also did the same thing by adding a function and seeing if both enters worked... and it did I dont understand what is happening, anyway ill keep looking into it... Thanks

**Comment by Mottie** [comment]
So, that demo is working as you'd expect it right?

I didn't think the `tagName` check was necessary since you had an ID on it; but it should have worked without it. So, I'm not sure why there would be a difference unless "**txtBox**AdminPass" was really a text box (as it is named) and not an input.

Oh, I did have to add this to the dialog initialization code ([demo](http://jsfiddle.net/Mottie/egb3a1sk/140/)):

```js
close: function(){
    $('#txtBoxAdminPass').getkeyboard().close();
}
```

because without that code, if you click the dialog box "x" to close it, the keyboard stays open.

**Comment by larivierec** [comment]
The demo worked at exactly as i'd expect, it's quite sad that the code is so similar and behaves differently

**Comment by Mottie** [comment]
I ran into an issue yesterday where I kept typing `.getkeyboard()` with a capital "K"... make sure to check for something minor like that too.

**Comment by larivierec** [comment]
i just noticed something, if i dont do
```javascript
$("#dialogPassword").dialog("close");
```
then it behaves correctly but the dialog doesnt disappear its reall weird

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.

**Comment by larivierec** [comment]
no, i havent figure it out. but you can close it.


Christopher Lariviere

Student in Software Engineering

**Comment by Mottie** [comment]
What was the remaining issue?

**Comment by larivierec** [comment]
its the same issue, no matter what code I put the enter key does not close
the dialog or the keyboard


Christopher Lariviere

Student in Software Engineering

**Comment by Mottie** [comment]
Can you modify one of the demo I shared to duplicate this issue. It would make it so much easier to troubleshoot the problem. Right now I'm just guessing.
