### ISSUE TITLE
Bower main js is different than the one in this repo

### ISSUE THREAD

**Issue by andreicojea** [Mottie/Keyboard#339]
The `dist/js/jquery.keyboard.min.js` file installed with bower has different content than the same file `dist/js` folder of this repo. They display the same version number though, but the bower one has an issue with meta keys...

**Comment by Mottie** [comment]
Hi @andreicojea!

The version on bower is the latest tagged version - it's the version you get when you download from the [releases page](https://github.com/Mottie/Keyboard/releases). The file in this repo is the most up-to-date. I try to name my commits "version bump", so you can see how many commits have been made since the last tagged version on the [commits page](https://github.com/Mottie/Keyboard/commits/master).

So, can you please give me some more detail about what's wrong with the meta keys? Can it be reproduced in a demo? Or could you [set up a demo](http://jsfiddle.net/Mottie/egb3a1sk/) showing the issue?

**Comment by andreicojea** [comment]
Seems to be fixed with version `1.22.2`, thank you :-) Basically the meta keys in custom layouts (like the iPad one) were completely inactive in version `1.22.1`

Thanks for this awesome lib, keep up the good work! :beers:
