### ISSUE TITLE
Is there any easy way of changing the font style?

### ISSUE THREAD

**Issue by brandflugan** [Mottie/Keyboard#347]
Hi! As the topic says I'm curious to know if there is an easy way of changing the font style. I'm not sure what's being used in the theme that I have (lightness) but it would be cool to change it to something else. 
Perhaps add this to the FAQ since it might be a common question. Sorry for posting this under the issues since it's not an issue really. 

Have a great day Mottie!

**Comment by Mottie** [comment]
Hi @brandflugan!

I do have a [FAQ entry](https://github.com/Mottie/Keyboard/wiki/FAQ#q-is-there-an-easy-way-to-change-the-size-of-the-keyboard) for changing the font-size of the keyboard. It's pretty much the same thing for changing the font-family & style.

The `keyboard.css` file for this plugin is really meant to be used as a guide. I wouldn't recommend changing the contents of the `keyboard.css` file directly since those changes will be lost if you update the repository. Instead, copy the desired parts of that file over into your page stylesheet.

Additionally, there is a wiki page about the [keyboard theme](https://github.com/Mottie/Keyboard/wiki/Theme). It lists all the class names used and what the HTML looks like of a rendered keyboard.

**Comment by brandflugan** [comment]
Hi again @Mottie! 
Sorry for being unclear, what I really ment was an option to change the actual font type. For example, if I want to use Helvetica Light, is there an easy way of changing it inside the css? Would be awesome if you have any idea on how to do it! 

Best regards
Markus

**Comment by Mottie** [comment]
I guess I'm still not completely understanding... 

* Do you mean the font type within the input? You can just target the input in the css and change the font.
* Or do you mean the preview input? In this case, if your input has an id, something like `dvorak`, then the keyboard that popups up will have an id of `dvorak_keyboard` (the `_keyboard` gets added on the end so you can target it for additional styling).
* Or do you mean dynamically changing the font from inside the keyboard?

**Comment by brandflugan** [comment]
Hi again! What I want is to change the font of the keyboard so it will fit the input that I have. All the button numbers & alphabetic letters should be in helvetica light in this project if it's possible.

**Comment by TheSin-** [comment]
@brandflugan I'm just curious to you understand CSS and how to change the font face with CSS?  I'm not trying to be rude at all I'm just curious since @Mottie did answer how in the first reply and my guess is that you just don't understand CSS and thus do not understand his reply.

As he stated font-family can be used in the stated files.  To help you see how that answers your question take a look here.  http://www.w3schools.com/cssref/pr_font_font-family.asp

**Comment by brandflugan** [comment]
@TheSin- I'm sorry, been a busy week and I completely missed out that Mottie answered the question already. I only read the font size and went too quick replying to him. I have some basic knowledge of css so I will look into that. I already tried to change it but I see that the jquery ui is causing it.
Sorry again.

**Comment by TheSin-** [comment]
no problem at all, again wasn't trying to be mean, just saw that this was going around in circles a little so thought I'd try and help both parties out ;) GL hope it works out for you.

**Comment by brandflugan** [comment]
No worries @TheSin-, I'm glad you saw what were causing the confusion :) Thanks for helping out!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
