### ISSUE TITLE
Can not chane lang

### ISSUE THREAD

**Issue by bzvyagintsev** [Mottie/Keyboard#390]
I set lang in keyoard.js 'ru', but keyboard still en.
how to change lang right?

**Comment by Mottie** [comment]
Hi @bzvyagintsev!

If you are using the built-in layouts, you'll need to load in the [`ru.js` file](https://github.com/Mottie/Keyboard/blob/master/dist/languages/ru.min.js) in the language folder. See [this demo](http://jsfiddle.net/Mottie/egb3a1sk/773/) for an example.

If you use any of the following files, *all currently translated languages*, which does include Russian, are included:

* `layouts/keyboard-layouts-combined.js` - All layouts except Microsoft & Greywyvern + all translated languages.
* `layouts/keyboard-layouts-microsoft.js` - All Microsoft layouts + all translated languages
* `dist/layouts/keyboard-layouts-greywyvern.min.js` - Minified version of all Greywyvern layouts + all translated languages
* `dist/layouts/keyboard-layouts-combined.min.js` - Minified version of combined layouts
* `dist/layouts/keyboard-layouts-microsoft.min.js` - Minified version of Microsoft layouts

The reason the `layouts/keyboard-layouts-greywyvern.js` file doesn't include translations is because this file is a direct conversion of all of the layouts from that site. No language translations were included & the file is not split up into individual layouts.

**Comment by bzvyagintsev** [comment]
Thanks! it seems works

One more question:

Is it possible to keyboard saves value to input automaticly/at the moment? without clicking on "accept" button?

**Comment by bzvyagintsev** [comment]
I find answer thank you
