### ISSUE TITLE
Disable key

### ISSUE THREAD

**Issue by traumatic** [Mottie/Keyboard#431]
Hi, I was wondering whether Keyboard provides a function which allows to disable keys.
E.g. in my case I want that the space key is disabled as long as text input is empty.

Thanks!

**Comment by Mottie** [comment]
Hi @traumatic!

If you look at the various demos available on the [Home wiki page](https://github.com/Mottie/Keyboard/wiki#how-to), you'll find this one - "Disable Accept & Bksp keys when preview is empty".

I took that demo and modified it to include the space: http://jsfiddle.net/Mottie/egb3a1sk/1161/

```js
$(function() {

  var toggleKeysIfEmpty = function( kb ) {
    var toggle = kb.$preview.val() === '';
    console.log( toggle, kb.$preview.val() );
    kb.$keyboard
      .find('.ui-keyboard-bksp, .ui-keyboard-accept, .ui-keyboard-space')
      .toggleClass('disabled', toggle)
      .prop('disabled', toggle);
  };

  $('#keyboard').keyboard({
    visible : function(e, keyboard) {
      toggleKeysIfEmpty( keyboard );
    },
    change: function (e, keyboard) {
      toggleKeysIfEmpty( keyboard );
    }
  });

});
```

Is that what you wanted?

**Comment by traumatic** [comment]
Thanks Mottie. That example works very well.

I replaced 
`var toggle = kb.$preview.val() === '';` with 
`var toggle = kb.$preview.val() === '' || kb.$preview.val().indexOf(" ") > -1;`

Now type any first letter and afterwards space. In my case that leads to multiple spaces being added.

**Comment by Mottie** [comment]
LOL, that is interesting....

When the space key is used, the `toggleKeysIfEmpty` function disables the space and thus prevents a "mouseup" event from firing. So, since there is no "mouseup" the keyboard starts firing a "repeater" event because it is set up to repeat the last key if it is held down.

I tried to clear the repeater in that function, but it still adds an extra space. So the easiest solution would be to set the `repeatRate` option to `0` - [demo](http://jsfiddle.net/Mottie/egb3a1sk/1162/).

I'll push a fix for this - that doesn't need `repeatRate` to be set to `0` - to the master branch in a minute.

**Comment by traumatic** [comment]
Wow, thanks for the quick fix Mottie. Keep up that great work!!
