### ISSUE TITLE
keyboard alway steal focus

### ISSUE THREAD

**Issue by jorgequinterob** [Mottie/Keyboard#441]
Hi All!

I have an asp.net website where we scan in one textbox a barcode. Then we show the keypad( in a tablet). We need to set the focus to this textbox when the page loads. 
But the keyborad always steal the focus, is there  a parameter to disable the initial focus? or how can we change the focus between our textboxes?

Thanks in advance

**Comment by Mottie** [comment]
Hi @jorgequinterob!

There is an [`initialFocus` option](https://github.com/Mottie/Keyboard/wiki/Usability#initialfocus) which can be set to `false` to prevent that behavior.

**Comment by jorgequinterob** [comment]
Yes im using this option:
 $('#txtNumkeyboard').keyboard({
            layout: 'num',
            restrictInput: true,
            preventPaste: true,
            initialFocus: false,
            display: {
                'a': 'Aceptar',
                'c': 'Cancelar'
            }

but the problem persist

**Comment by Mottie** [comment]
How about using [`noFocus`](https://github.com/Mottie/Keyboard/wiki/Usability#nofocus) ([demo](http://jsfiddle.net/egb3a1sk/1218/))?

If that doesn't work, then please modify the above demo so I can better troubleshoot the issue.

**Comment by jorgequinterob** [comment]
ready is modified  [http://jsfiddle.net/egb3a1sk/1218/](url)

**Comment by Mottie** [comment]
After that demo is modified, you need to press "Update" then copy the new URL here. Thanks!

**Comment by jorgequinterob** [comment]
sorry, [http://jsfiddle.net/egb3a1sk/1243/](url)

**Comment by Mottie** [comment]
[This](http://jsfiddle.net/egb3a1sk/1244/) was the best I could do with the demo provided... the div was hidden and I modified the asp element format. Would you share the *rendered* HTML if the steps below don't provide a solution?

Is it still stealing away the focus? The input/textarea doesn't even get a caret, or highlighted. Maybe the easiest thing to do would be to add a `visible` callback to give focus to your element after clicking on a virtual keyboard keys or div because the click does give that element focus ([demo](http://jsfiddle.net/egb3a1sk/1245/)):

```js
visible: function(e, keyboard) {
  keyboard.$keyboard.add(keyboard.$allKeys).on('click', function() {
    $('#main').focus();
  });
}
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
