### ISSUE TITLE
Capslock & stickyShift seem to be broken, not fixed, by commit 663b8 on Jan 18th

### ISSUE THREAD

**Issue by IanMcGarry** [Mottie/Keyboard#452]
663b86dfba6d1dece66809b1b290f8542730a5ab (capLock key now "sticks" properly, jan 18 )

if I change:
`if (!base.capsLock || !o.stickyShift && !e.shiftKey) {`
back to:
`if (!base.capsLock && !o.stickyShift && !e.shiftKey) {`
then stickyShift and caps lock behave perfectly fine for me

**Comment by Mottie** [comment]
Hi @IanMcGarry!

Hmm, so it doesn't behave the way it is now? It make more sense to me that the caplock detection is separate from the stickyshift. I pretty much don't have any layouts with a capslock key and I leave my caplock key disabled through my OS, so I don't test this very often :P

Once all browsers support it, and I drop older browser support, I'll switch to use the [`getModifierState` function](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState) to get the actual capslock state instead of guessing at it ([demo](http://jsfiddle.net/Mottie/a6nhqvv0/)).

**Comment by IanMcGarry** [comment]
Hi Mottie,
Thanks for the quick reply.
I don't use capslock in the layout, i was using it from the physical keyboard.
Check out this example. [demo](http://jsfiddle.net/430g4qfb/)
Capslock (from physical keyboard) works perfectly fine, but the stickyShift option does not.
If I change that || back to && , then both work fine. I haven't tested a layout with a capslock key

**Comment by Mottie** [comment]
Ok, thanks! It looks like you are correct. I'll get that change reverted as soon as I can get this grunt update to behave.
