### ISSUE TITLE
input focus is lost (blured) after accept/cancel

### ISSUE THREAD

**Issue by acc15** [Mottie/Keyboard#473]
input focus is lost (blured) after accept/cancel.

This completely breaks following tab navigation.

Also if u place 2 inputs horizontally and trying to quickly switch between them, then sometimes keyboard dont't appear at all.

Demo: https://jsfiddle.net/rwhzgaab/1/

Browser:
Chrome Version 50.0.2661.102 (64-bit)

**Comment by Mottie** [comment]
Hi @acc15!

In that demo, the `switchInput` option is defined as an empty function:

```js
switchInput: function(keyboard, goToNext, isAccepted) {}
```

Because it is defined, it overrides the build-in behavior. If you remove, or comment it out, the tab should work as expected - [demo](https://jsfiddle.net/Mottie/rwhzgaab/2/).

**Comment by acc15** [comment]
Oh, wow. 

Looks like `switchInput` really helps with tab nav. Thank you!

But still sometimes keyboard dont appear after focus. 
I've prepared a short video to demonstrate an issue:

https://youtu.be/xfJaE94rE1c (from 0:10 to 0:40)

Please take a look. Maybe i'm missing some options again?

**Comment by Mottie** [comment]
LOL, those are some *mad* clicking skillz...

There is going to be a delay when clicking between inputs. Not every browser behaves, so there is a small delay from focus to closing one keyboard and opening the next. This is because clicking on a key in the virtual keyboard takes focus away from the input, so it has to add it back in case the user types on the physical keyboard. We don't want the keyboard to close in the mean time.

Some things to note/try:

* If you want to tab backwards (from B to A) use <kbd>Shift</kbd> + <kbd>Tab</kbd>.
* If you want the accept button to *not* close the keyboard, set the [`stayOpen` option](https://github.com/Mottie/Keyboard/wiki/Usability#stayopen) to `true`. The keyboard will stay open until another input has focus or until the user accepts the value... 
* To prevent the accept button from closing the keyboard, you can [modify an action key](https://github.com/Mottie/Keyboard/wiki/Actions#modify-an-action-key), the accept button in this case, to not close the keyboard.

**Comment by acc15** [comment]
`Shift+Tab` yeah. Tab nav works as expected.

`stayOpen` doesn't help here. 
Will you consider fixing that?

**Comment by Mottie** [comment]
Did you try modifying the accept action key?

I'm not exactly sure what you are asking me to fix... the keyboard does lose focus if you click super fast. I can reduce the focus timer, but then you'll have issues in IE.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
