### ISSUE TITLE
How to make meta not switch to normal

### ISSUE THREAD

**Issue by terrylinooo** [Mottie/Keyboard#474]
Click on the meta button to show meta defined keyboard, click on it again will go back to normal keybaord, It makes users confusing about what is the current keyboard they are using, so I would like to make double-clicking meta button will stay on meta keyboard, does anyone know how to do that?

Thanks!!

**Comment by Mottie** [comment]
Hi @terrylinooo!

I'm not sure why your user would be confused since the meta key highlights when active ([demo](http://jsfiddle.net/Mottie/egb3a1sk/1686/)).

Anyway, it is possible, but you'd have to unbind the meta keys once the keyboard is visible, then add your own binding to activate the meta keyaction ([demo](http://jsfiddle.net/Mottie/egb3a1sk/1687/)):

```js
visible: function(e, kb){
  kb.$keyboard.find('[data-name^="meta"]')
    .unbind('mousedown' + kb.namespace)
    .bind('dblclick', function(){
      $.keyboard.keyaction.meta(kb, this);
    })
    // add note to title
    .each(function(){
      this.title += " (double click to activate)";
    });
}
```
