### ISSUE TITLE
Is it possible to bring ctrl key ?

### ISSUE THREAD

**Issue by gibyalex** [Mottie/Keyboard#486]
Hi 
I am new to this  keyboard functionality , I have requirement  that  need to have a virtual keyboard  layout which need to support  Ctrl  key .

Will this  utility support the same ? Is there documentation is there for the same

**Comment by Mottie** [comment]
Hi @gibyalex!

Are you asking if the keyboard supports stuff like <kbd>Ctrl</kbd> + <kbd>a</kbd> to select all text, and such? If so, then yes.  You can also disable pasting content into the input using the [`preventPaste` option](https://github.com/Mottie/Keyboard/wiki/Usability#preventpaste).

If you're asking if it is possible to add a Ctrl keyset, then no it does not currently provide that ability.

Can you describe your use case? Or explain how you expect the Ctrl key to behave.

**Comment by gibyalex** [comment]
Hi @Mottie ,

I was looking for Ctrl + a  functions    , And Can you guide me how to enable and disable Keys in the layout ? 
such just how to bring Ctrl or Alt key in the layout and support the features

**Comment by Mottie** [comment]
So, you're asking to add a button to select all text, copy and paste? To copy and paste content, you can use [`document.execCommand`](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand), but it isn't supported in all browsers. If you need to support all browsers, use a clipboard library.

Anyway, here is a demo adding a copy and paste button: http://jsfiddle.net/Mottie/egb3a1sk/1915/ - **Strangely, I can't actually get the paste `execCommand` to work** But then I can't get it to work in the other demos I found. 

And since I don't know which keys you want to disable, here is a demo from the [home wiki page](https://github.com/Mottie/Keyboard/wiki) (which has lots of demos) that disables the Accept and Bksp keys when the input is empty: https://jsfiddle.net/Mottie/u0g4u5c8/
