### ISSUE TITLE
problem with clicking shift on touch screen

### ISSUE THREAD

**Issue by Suka1215** [Mottie/Keyboard#513]
When I click shift on a touch screen the keyboard switches to uppercase and then switches back to lowercase by itself. If I manage to get uppercase and click a letter it stores a lowercase letter in the input. I would appreciate any help with this.

**Comment by Mottie** [comment]
Hi @Suka1215!

If you want the shift to "stick" set the [`stickyShift` option](https://github.com/Mottie/Keyboard/wiki/Usability#stickyshift) to `true` ([demo](http://jsfiddle.net/Mottie/Em8sG/4086/)).

The demo from issue #81 won't work with the `stickyShift` option set because the `change` callback would disable the shift because the code was looking for a period to the left of the caret, and if it wasn't there, the key set would be set to "normal" (non-shift).

**Comment by Suka1215** [comment]
Thanks for the quick response Mottie. I may have mis spoke. I don't want shift to stick. I am needing to hit it once enter a capital letter and have it go back to lower case. Problem it when it switches to uppercase and I hit the uppercase letter it doesn't put and uppercase in the input... just lowercase. But only on touch screen with my finger.

**Comment by Suka1215** [comment]
I guess I was wondering how we ensure that pressing shift on a touch screen selects and ensures that uppercase is entered into the input. Or you could point me to what lines in the library deal with that functionality.

**Comment by Mottie** [comment]
I am not able to duplicate that issue. I've tried it on my Android tablet & phone. Is this issue only showing up for you on a specific device? Are you seeing the issue on the [main demo page](https://mottie.github.io/Keyboard/)?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
