### ISSUE TITLE
autocomplete - problem with ajax/json response

### ISSUE THREAD

**Issue by MarcAckermann** [Mottie/Keyboard#516]
Hi, 
this is a new issue in version 1.26.14:

The data returned for the autocomplete via ajax/json is in the standard jQuery autocomplete format
[{label:"Donald Duck", "value":1}, {label:"Mickey Mouse", "value":2}]
This is causing a problem now. See this [jsFiddle](http://jsfiddle.net/kzsLa7h0/).

TypeError: base.last.val.substring is not a function
jquery.keyboard.js (Line 628)

If I change the type of the value variable from int to string it is working fine:
[{label:"Donald Duck", "value":"1"}, {label:"Mickey Mouse", "value":"2"}]

**Comment by Mottie** [comment]
Hi @MarcAckermann!

Thank you for reporting this issue. I started working on a solution late last night, but apparently, there are a few other issues when setting the source data as an object. I'll try to get this fixed today!

**Comment by Mottie** [comment]
I just opened this ticket for jQuery UI: https://bugs.jqueryui.com/ticket/15130#ticket

When hovering an item with the mouse, the input shows the highlighted item. But when using keyboard navigation, the source value is shown instead of the source label.

Demo: http://jsbin.com/koregobilu/edit?html,output

![dev](https://cloud.githubusercontent.com/assets/136959/22358314/ad9db854-e403-11e6-8193-e51385a02b5e.gif)

Other than that, I think I have a working fix, which I will push to the master branch very soon.

**Comment by Mottie** [comment]
Ok, the keyboard should be all fixed now! Your demo - http://jsfiddle.net/kzsLa7h0/ - should work now, but it will have the keyboard navigation problems I've noted above.

It's odd but in the [JSBin demo](http://jsbin.com/koregobilu/edit?html,output) pressing <kbd>Enter</kbd> or using a mouse-click will result in the value being added to the input instead of the label; but the jsFiddle that uses this virtual keyboard doesn't seem to have the same issue with the selecting of the autocomplete item. Maybe there is another difference I didn't notice.

Anyway, I've also submitted a fix for the [jQuery UI autocomplete widget](https://github.com/jquery/jquery-ui/pull/1792), so either wait for that, or don't use a source object.

**Comment by MarcAckermann** [comment]
Hi, thank's for the quick fix! Running smooth now. Yeah, I noticed the keyboard problem but this is not crucial for me at the moment since the app that I'm developing runs on terminals that don't have keyboards.

**Comment by Mottie** [comment]
Well, I guess that is expected behavior...

> scottgonzalez:
> The value is supposed to be inserted into the text field. The [​documentation](http://api.jqueryui.com/autocomplete/#option-source) even says so. The bug is that the label gets inserted with hover, not that the value gets inserted with keyboard navigation.

In the documentation:

> The label property is displayed in the suggestion menu. The value will be inserted into the input element when a user selects an item.
