### ISSUE TITLE
Call accept button when i click on autocomplete

### ISSUE THREAD

**Issue by cristo1985** [Mottie/Keyboard#546]
Hi Mottie again,
ehm when i click on autocomplete how can i perform accept button?
Thanks

**Comment by Mottie** [comment]
Hi @cristo1985!

I don't think that would be a very good user experience. If they accidentally select an option and change their mind, at least they still have the cursor inside the input and can backspace or delete the word. If you close the keyboard immediately after they select something, it makes for a very abrupt experience.

That being said, you can use jQuery UI's autocomplete [`select` callback function](http://api.jqueryui.com/autocomplete/#event-select) and trigger the keyboard to accept and close - [demo](https://jsfiddle.net/Mottie/n6xeoLyp/28/)

```js
$('#keyboard')
  .keyboard()
  .autocomplete({
    source: availableTags,
    select: function(event, ui) {
      $('#keyboard').getkeyboard().accept();
    }
  })
  .addAutocomplete();
```

That said, I would prefer to use GitHub issues to report issues or ask for enhancements. Please use the [gitter chatroom](https://gitter.im/Mottie/Keyboard) or [Stack Overflow](http://stackoverflow.com/questions/tagged/virtual-keyboard) to ask questions about this plugin instead of opening a new issue. Thanks!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by cristo1985** [comment]
Sorry i had an accident and i was unable to write to pc.... for months.. sorry... thanks for any help!
