### ISSUE TITLE
Double tap enter and tab with touchscreen

### ISSUE THREAD

**Issue by movitch** [Mottie/Keyboard#579]
Hi,

I have a problem that I can not solve for several days so I can ask for your help.
I use the virtual keyboard with a form, it works very well with Chrome. When I use the same form with a touch screen (on raspberry pi and chromium), when I press enter or tab on the virtual keyboard, the action is done systematically twice. You can see the mouse pointer click 2 times in a row. This is done only on the keys enter and tab and only with the touch screen, other key are ok. If I plug a mouse on the raspberry and I click, it works correctly. Would you have an idea because I am lost. Thank you in advance for your help.

**Comment by Mottie** [comment]
Hi @movitch!

Hmm, that is unusual. I haven't ever tested the keyboard on a raspberry pi so I don't have a definite solution, but there are a few things you can try:

* Remove either of the named events (`'mousedown touchstart'`) from the [keyBinding](https://github.com/Mottie/Keyboard/wiki/Usability#keybinding) option string. Or switch to using [jQuery's PEP](https://github.com/jquery/PEP) and use `'pointerdown'` instead.
* Set the [`preventDoubleEventTime` option](https://github.com/Mottie/Keyboard/wiki/Usability#preventdoubleeventtime) to a value higher than `100` (ms). This sets a time interval where events triggered after the last event are ignored. I wouldn't set it too high, like more than `200` ms because it will drop events for fast typers.
* Turn off the key repeater (press and hold a key to make it repeat), by setting the [`repeatRate` option](https://github.com/Mottie/Keyboard/wiki/Usability#repeatrate) to zero.

If none of that works, I'll probably have to get you to add some logs to the event code.

**Comment by movitch** [comment]
Hi @Mottie ,

Thank you very much for your help.
Switch to using PEP and 'pointerdown' seems to solve the problem for me.

It's strange. The problem was only on tab and enter key with navigation on and no repetition problem with other key.

Best regards
