### ISSUE TITLE
Custom virtual keyboard

### ISSUE THREAD

**Issue by goorgoor** [Mottie/Keyboard#641]
Hi,

This is not an issue, rather scream for help! I'm working on a dictionary site my mother tongue. The phonetic is written in latin/english alphabet with these extra letters Üü Ââ Šš Žž Čč Əə Γγ

I have no idea how to edit this: https://mottie.github.io/Keyboard/docs/basic.html so that i can add those extra letters to it. I only need to replace 1,2,3... to "=" and also "[" and "]", as shown in the image below i have tried to customize, but i have not idea that i need to change anything else! 

I have done this to the jquery.keyboard.js:
	
```
'qwerty': {
			'normal': [
				'` Ü ü Â â Š š Ž ž Č č Ə ə {bksp}',
				'{tab} q w e r t y u i o p Γ γ \\',
				'a s d f g h j k l ; \' {enter}',
				'{shift} z x c v b n m , . / {shift}',
				'{accept} {space} {cancel}'
			],
			'shift': [
				'~ ! @ # $ % ^ & * ( ) _ + {bksp}',
				'{tab} Q W E R T Y U I O P { } |',
				'A S D F G H J K L : " {enter}',
				'{shift} Z X C V B N M < > ? {shift}',
				'{accept} {space} {cancel}'
			]
		},
```

![screenshot-mottie github io-2018-01-14-15-24-59-990](https://user-images.githubusercontent.com/19527211/34916965-26f75f14-f940-11e7-80ca-95027ae6c25e.png)

is changed to this:

![screenshot--2018-01-14-15-45-18-634](https://user-images.githubusercontent.com/19527211/34917095-08149510-f942-11e7-843a-d6b77f14c134.png)

This is the field i have on my "add word" page. I guess i just need to add 'id="keyboard"' to the code below to make the keyboard appear, right? 

` <input type="text" class="form-control"   placeholder="فونتیک را وارد کنید" name="pePhSen"  value= "-" ></div>`

Appriciate any help i can get! Cheers

**Comment by Mottie** [comment]
Hi @goorgoor!

You almost got it. To add a custom layout, set the [`layout` option](https://github.com/Mottie/Keyboard/wiki/Layout#layout) to `'custom'` then add the normal and shift definitions to the [`customLayout` option](https://github.com/Mottie/Keyboard/wiki/Layout#customLayout); also, check to see if your [layout](https://github.com/Mottie/Keyboard/tree/master/dist/layouts) is available. If not, then this is the needed code to set up a custom layout:

```js
$(function() {
  $('#keyboard').keyboard({
    // language: ['myLanguage'],
    layout: 'custom',
    customLayout: {
      'normal': [
        '` Ü ü Â â Š š Ž ž Č č Ə ə {bksp}',
        '{tab} q w e r t y u i o p Γ γ \\',
        'a s d f g h j k l ; \' {enter}',
        '{shift} z x c v b n m , . / {shift}',
        '{accept} {space} {cancel}'
      ],
      'shift': [
        '~ ! @ # $ % ^ & * ( ) _ + {bksp}',
        '{tab} Q W E R T Y U I O P { } |',
        'A S D F G H J K L : " {enter}',
        '{shift} Z X C V B N M < > ? {shift}',
        '{accept} {space} {cancel}'
      ]
    }
  })
  // activate the typing extension
  .addTyping({
    showTyping: true,
    delay: 250
  });
});
```

This layout may not be ideal since it does replace the number keys. Hopefully, your [language layout](https://github.com/Mottie/Keyboard/tree/master/dist/languages) is already available. If not, you can follow the [`language` option](https://github.com/Mottie/Keyboard/wiki/Language) instructions to set up a file with the needed translations, then update the `language` option, seen in the code above, using the set name. There is also a [language template](https://github.com/Mottie/Keyboard/blob/master/languages/_language_template.js) to use as needed.

**Comment by goorgoor** [comment]
Thanks! It works now...i tried to add several id="keyboard" on one page, but that does work for one field :( Can you please give me a solution.

**Comment by Mottie** [comment]
All `id`s must be unique. Instead add a class:

```html
<input class="keyboard" type="text">
```

then use `$(".keyboard")` instead of `$("#keyboard")`.

**Comment by goorgoor** [comment]
Thanks that solved my problem! Bless you.
