### ISSUE TITLE
Change CSS based on Keyboard

### ISSUE THREAD

**Issue by yantw4** [Mottie/Keyboard#667]
This is more of a question than an issue.  I'm trying to modify the size of the new keyset when switching keysets.  The goal is to have the buttons be larger when only numbers are shown and then smaller with a full keyboard to fit a mobile device.

![image](https://user-images.githubusercontent.com/19982530/38958169-724474aa-432a-11e8-9a85-4afb60d03b66.png)

The keyaction.shift function is working as expected.  I'm finding that I can change the css on the original keyset using $(el).parent().children().css, but I'm having difficulty figuring out how to reference the new keyset.  Any help would be appreciated.

Something along these lines..
![image](https://user-images.githubusercontent.com/19982530/39051105-b40393e8-4475-11e8-87ea-438ceb5e4188.png)

**Comment by Mottie** [comment]
Hi @yantw4!

Since the num pad is defined within the "normal" keyset, you can target the keyset container using `.ui-keyboard-keyset-normal`, then increase the font-size.

```css
.ui-keyboard-keyset-normal {
 font-size: 1.5em;
}
```

You can also target individual keys based on the characters inside. I've tried to explain it in detail in the [theme wiki page](https://github.com/Mottie/Keyboard/wiki/Theme). Please let me know where I can make the instructions more clear.

**Comment by yantw4** [comment]
Thanks, that's very helpful.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
