### ISSUE TITLE
Don`t work well when click too fast

### ISSUE THREAD

**Issue by HZzzzy** [Mottie/Keyboard#677]
when I click the input area with a speed of twice per second, the virtual keybord may not appear, such as clicking fastly 5 times or more, it my happen once.

**Comment by Mottie** [comment]
Hi @HZzzzy!

I just tried double clicking in Chrome on my desktop and it opens every time. What is the particular OS, browser and virtual keyboard version you're using where this issue occurs?

**Comment by HZzzzy** [comment]
windows ultimate with service pack 1, chrome version 67.0.3396.79 and the version of virtual keyboard is 1.28.3, the issue occurs only when I click fastly, but opens every time when clicking with a normal speed

**Comment by Mottie** [comment]
Hmm, I can't duplicate what's being described. Would you please share a screen cast?

**Comment by HZzzzy** [comment]
[Screenshot.zip](https://github.com/Mottie/Keyboard/files/2169138/Screenshot.zip)
unzip this file and open in browser, in the screen record, you can see the issue I desctibed

**Comment by HZzzzy** [comment]
Would you mind to give me a notice when you fixed it?

**Comment by Mottie** [comment]
Well, it *seems* the issue is due to a 500ms delay before rebinding the focus event on the input/textarea. This was originally added to fix an issue in IE9 (see #72). I don't know if there is still a need for this keyboard in IE9, so instead of removing the delay, I reduced it to 200ms. Please let me know if you still encounter this issue. If you're faster than 200ms, maybe you should make gaming as a career 😉!

**Comment by HZzzzy** [comment]
to be honest, I think it is not a problem in daily use，but my PM thought it would impact user experience, I will update the keyboard plugin and try it again, thanks a lot
