### ISSUE TITLE
Merging Two Word 

### ISSUE THREAD

**Issue by Yateenp88** [Mottie/Keyboard#769]
i have query regarding joining two word and form different single word.Please help

**Comment by Mottie** [comment]
Hi @Yateenp88!

You can't use the [combo](https://github.com/Mottie/Keyboard/wiki/Language#comboregex---regexp)'s feature because it only examines the last two characters that were typed, this was done to prevent replacements from _always_ occurring.

But, good news, you can use the [`change` callback](https://github.com/Mottie/Keyboard/wiki/Methods#change) to alter the text of the input ([demo](https://jsfiddle.net/Mottie/avjg0L6z/))

```js
$(function() {
  var wordsToChange = 'two words';
  var newWord = 'oneNEWword';

  $('#keyboard').keyboard({
      change: function(event, kb) {
        var $el = kb.$preview;
        var text = $el.val();
        if (text.includes(wordsToChange)) {
          var newText = text.replace(wordsToChange, newWord);
	        $el.val(newText);
          // move caret to end of new word
	        $.keyboard.caret($el, newText.indexOf(newWord) + newWord.length);
        }
      }
    })
    // activate the typing extension
    .addTyping({
      showTyping: true,
      delay: 250
    });
```

In that demo:

* Click the keyboard icon next to the input to get it to start typing. Once it's done, enter "o" to see the change happen.
* It doesn't seem like you can use `addTyping` to update the input, but you can. You'll need to change the code to use an event listener for the [`keyboardChange` event](https://github.com/Mottie/Keyboard/wiki/Methods#events) and look for the text to change, thenin the `addTyping` callback, trigger this event.
* I set the caret position to be at the end of the new word. If you want it somewhere else, or to not move at all, remove the `$.keyboard.caret` line.
* I only set the demo up for one set of word replacements, but it can be set it up for more than one set. If you need help with this, please feel free to ask.

**Comment by Yateenp88** [comment]
thanks buddy....help me lots

**Comment by Yateenp88** [comment]
is combo's limited for ligature character only..

**Comment by Mottie** [comment]
> is combo's limited for ligature character only

No, any two characters can be used. I think I'll add an option to expand this limit.
