### ISSUE TITLE
Shift key should not act as caps lock

### ISSUE THREAD

**Issue by RABensoussan** [Mottie/Keyboard#792]
Why does the shift key act as a caps lock? On a regular keyboard the shift key means "make this **one letter** caps" and caps lock means "make **all letters** caps til I click you again". Is there a method or way to have the shift key turn on the caps for just one keypress?

**Comment by Mottie** [comment]
Hi @RABensoussan!

The shift key will only have that behavior if you set the [`stickyShift` option](https://github.com/Mottie/Keyboard/wiki/Usability#stickyshift) to `true`. Otherwise, it should only apply to the first letter typed after using the shift.

If that doesn't turn out to be the problem, please [modify this demo to show the problem](http://jsfiddle.net/Mottie/egb3a1sk/).

**Comment by RABensoussan** [comment]
Thanks, that was it! Tried looking through the options today and couldn't find it. Why is that the default? Shouldn't it act like a keyboard? I wasn't setting it to true...to fix it now I specifically set it to false.
Either way, thanks again
